_wandb:
    value:
        cli_version: 0.26.1
        e:
            6gjadnuupj40pk0g4cuh4e87vrkjujbr:
                codePath: negotiation-env\training\train_grpo.py
                codePathLocal: training\train_grpo.py
                email: thirstyexams1990@gmail.com
                executable: C:\Users\nanda\Desktop\MetaXOpenEnv\negotiation-env\venv\Scripts\python.exe
                git:
                    commit: e2edaadf4626b2a8c3e89f2cbf0f37eb654cb84e
                    remote: https://github.com/AUXID-01/MetaXOpenEnv.git
                host: LAPTOP-PHLCSEQ1
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\nanda\Desktop\MetaXOpenEnv\negotiation-env\training\train_grpo.py
                python: CPython 3.11.0
                root: C:\Users\nanda\Desktop\MetaXOpenEnv\negotiation-env
                startedAt: "2026-04-25T19:33:20.502694Z"
                writerId: 6gjadnuupj40pk0g4cuh4e87vrkjujbr
        m: []
        python_version: 3.11.0
        t:
            "3":
                - 16
            "4": 3.11.0
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
max_turns:
    value: 15
model:
    value: unsloth/Qwen2.5-1.5B-Instruct
stage:
    value: 1
